### PR TITLE
fix - build full url when use baseUrl and relative path together

### PR DESCRIPTION
**Pull request by imanabbasi**

### CODE REVIEW

**Comment by cuibonobo** [comment]
The existing code already does this without needing to import from `axios`:
```javascript
const onlyUrl = new URL("http://example.com");            // result: http://example.com
const onlyBase = new URL("", "http://example.com");       // result: http://example.com
const urlAndBase = new URL("/foo", "http://example.com"); // result: http://example.com/foo
```

**Comment by imanabbasi** [comment]
Hi @cuibonobo 
I know, The URL interface is used to parse, construct, normalize, and encode [URLs](https://developer.mozilla.org/en-US/docs/Glossary/URL). It works by providing properties which allow you to easily read and modify the components of a URL.
But it can't handle some exception, for example :
```js
const url = new URL("/foo", "http://example.com/api/v1.0/"); // result: http://example.com/foo
// result should be: http://example.com/api/v1.0/foo
```
What do you think about it?

**Comment by cuibonobo** [comment]
Ok, now I understand your use-case. (Please provide a description for your PR in the future.)

A difficulty that I still have with this PR is that it imports from Axios libraries. This presents a difficulty for testing because Axios should not be a direct dependency of this repo. Not even a peer dependency!

Obviously this is a `fetch` adapter for Axios, so it's understood that Axios is on the system somewhere, but it isn't always explicit. For example, in one of my applications Axios is a sub-dependency of the Square SDK. As a result, my application doesn't explicitly import `axios`. If this repo were to list `axios` as a peer dependency it would throw an error.

In this context, how can we achieve the behavior you are expecting and run tests properly?

**Comment by cuibonobo** [comment]
@imanabbasi The functionality you were looking for is now available in v0.4.0 on NPM.

**Comment by imanabbasi** [comment]
Hi @cuibonobo 
I think it's better to prepare helper methods, **buildURL** and **buildFullPath** like axios and use them in project.
in this way, there is no dependency like axios and can be test easily :smile: 
like these:
https://github.com/axios/axios/blob/v1.x/lib/helpers/buildURL.js
https://github.com/axios/axios/blob/v1.x/lib/core/buildFullPath.js
What's your idea?

**Comment by cuibonobo** [comment]
Version `0.4.0` already incorporates the `buildFullPath` function and achieves the functionality you were looking for. I wrote a new issue (#4) to add the functionality from `buildURL`.

**Pull request closed without merging**
